import Head from 'next/head'
import styles from '../styles/Container.module.css'

const Container = (props) => {
  const { title, children } = props; 
  return (
    <div className={styles.container}>
      <Head>
        <title>{title} - Game Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{title}</h1>
        {children}
      </main>

      <footer className={styles.footer}>
        <span>2022 Bethany Dunfield</span>
      </footer>   
    </div>
  )
};

export default Container;