import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Container.module.css'

const Container = (props) => {
  const { title, children } = props; 
  return (
    <div className={styles.container}>
      <Head>
        <title>{title} - Game Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <Link href="/">Games</Link>
        <Link href="/add">Add Game</Link>
        <h1 className={styles.mainTitle}>Illie's Game Tracker</h1>
      </nav>
      <main className={styles.main}>
        <h2 className={styles.pageTitle}>{title}</h2>
        {children}
      </main>

      <footer className={styles.footer}>
        <span>2022 Bethany Dunfield</span>
      </footer>   
    </div>
  )
};

export default Container;